#!/usr/bin/env php
<?php
require_once __DIR__ . '/common.php';

$consoleCfgObj = \CjsConsole\ConsoleConfig::getInstance()->setEnvironments(env('APP_ENV', 'dev'))->setDebug(true);

if(env('APP_ENV', 'dev') != 'dev') {
    $consoleCfgObj->setCrontabEntryPath("/data1/www/hf_entrance/console/microservice")->setPrefixArtisan(" artisan jigou-service ");
} else {
    $consoleCfgObj->setCrontabEntryPath(__DIR__ . '/');
}

$input = new \CjsConsole\Input\ArgvInput();//分析cli对象
$consoleAppObj = \CjsConsole\ConsoleApp::getInstance("cjs console", '1.0.0');
$kernel = new \ConsoleDemo\Kernel($consoleAppObj);//注入app对象

$scheduleObj = new \CjsConsole\Scheduling\ScheduleRunCommand($consoleAppObj->getSchedule());
$consoleAppObj->add($scheduleObj);//新增命令

$makeConsoleObj = new \CjsConsole\Command\MakeConsoleCommand();
//$makeConsoleObj->setStubFile(__DIR__ . '/doc.md');
$consoleAppObj->add($makeConsoleObj->setAppPath(__DIR__)->setAppNamespace('ConsoleDemo'));//新增 make:console命令

//var_export(array_keys($consoleAppObj->getCommands())); //打印所有命令名
$status = $kernel->handle($input, new \CjsConsole\Output\ConsoleOutput());
$kernel->terminate($input, $status);

exit($status);

