#!/usr/bin/env php
<?php
require_once __DIR__ . '/common.php';

$consoleCfgObj = \CjsConsole\ConsoleConfig::getInstance()->setEnvironments('dev')->setDebug(true);

if(env('APP_ENV', 'dev') != 'dev') {
    $consoleCfgObj->setCrontabEntryPath("/data1/www/hf_entrance/console/microservice")->setPrefixArtisan(" artisan jigou-service ");
} else {
    $consoleCfgObj->setCrontabEntryPath(__DIR__ . '/');
}

$input = new \CjsConsole\input\ArgvInput();
$ConsoleObj = \CjsConsole\ConsoleApp::getInstance("cjs console", '1.0.0');
$kernel = new \ConsoleDemo\Kernel($ConsoleObj);

$scheduleObj = new \CjsConsole\Scheduling\ScheduleRunCommand($ConsoleObj->getSchedule());
$ConsoleObj->add($scheduleObj);//新增命令

$makeConsoleObj = new \CjsConsole\Command\MakeConsoleCommand();
$ConsoleObj->add($makeConsoleObj->setAppPath(__DIR__)->setAppNamespace('App'));//新增命令

//var_export(array_keys($ConsoleObj->getCommands())); //打印所有命令名
$status = $kernel->handle($input, new \CjsConsole\Output\ConsoleOutput());
$kernel->terminate($input, $status);

exit($status);

